language: go

os:
  - linux
  - osx

go:
  - 1.11.x
  - master

env:
  - GO111MODULE=off
  - GO111MODULE=on

matrix:
  allow_failures:
    - go: master

go_import_path: gosh-lang.org/gosh

install:
  - make init

script:
  - gofmt -w -s .
  - make test
  - git diff --exit-code
  - make check

after_success:
  - bash <(curl -s https://codecov.io/bash) -f cover.out -X fix -e GO111MODULE
